# TeamBundle Routes
teams:
  resource: "@TickitTeamBundle/Resources/config/routing.yml"
  prefix: /teams

# UserBundle Routes
users:
  resource: "@TickitUserBundle/Resources/config/routing.yml"
  prefix: /users

projects:
  resource: "@TickitProjectBundle/Resources/config/routing.yml"
  prefix: /projects

# PreferenceBundle Routes
preferences:
  resource: "@TickitPreferenceBundle/Resources/config/routing.yml"
  prefix: /preferences

# PermissionBundle Routes
permissions:
  resource: "@TickitPermissionBundle/Resources/config/routing.yml"
  prefix: /permissions

# DashboardBundle Routes
dashboard:
  resource: "@TickitDashboardBundle/Resources/config/routing.yml"

# FOSUserBundle Routes
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

fos_user_group:
  resource: "@FOSUserBundle/Resources/config/routing/group.xml"
  prefix: /group