Tickit\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: username
            message: Looks like someone is already using that username, could you try something else?
    properties:
        forename:
            - Length: { max: 120, maxMessage: "Forename is too long, try something a little shorter (120 characters max)" }
            - NotBlank: { message: "You didn't provide a forename, did you forget it?" }
        surname:
            - Length: { max: 120, maxMessage: "Surname is too long, try something a little shorter (120 characters max)" }
            - NotBlank: { message: "You didn't provide a surname, did you forget it?" }
        group:
            - NotBlank: { message: "You didn't select a group, did you forget?" }
        email:
            - Email:
                message: That email "{{ value }}" doesn't look valid. Could you double check it?
                checkHost: true